name: table_tennis
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  uuid: ^4.5.2
  excel: ^4.0.6
  file_picker: ^8.1.7
  collection: ^1.18.0
  path_provider: ^2.1.3
  pdf: ^3.11.1
  printing: ^5.13.2
  window_manager: ^0.4.3
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  sqlite3_flutter_libs: ^0.5.20 # [추가] 윈도우용 SQLite 바이너리 포함

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.16.13

flutter:
  uses-material-design: true

  fonts:
    - family: SJ세종고딕
      fonts:
        - asset: assets/fonts/SJ세종고딕R.ttf
        - asset: assets/fonts/SJ세종고딕L.ttf
          weight: 300
        - asset: assets/fonts/SJ세종고딕B.ttf
          weight: 700
        - asset: assets/fonts/SJ세종고딕EB.ttf
          weight: 900
    - family: SJ정글고딕
      fonts:
        - asset: assets/fonts/SJ정글고딕.ttf
    - family: SJ고은명조
      fonts:
        - asset: assets/fonts/SJ고은명조M.ttf
        - asset: assets/fonts/SJ고은명조L.ttf
          weight: 300
        - asset: assets/fonts/SJ고은명조B.ttf
          weight: 700
    - family: SJ정글명조
      fonts:
        - asset: assets/fonts/SJ정글명조R.ttf
        - asset: assets/fonts/SJ정글명조L.ttf
          weight: 300
    - family: SJ상큼오렌지
      fonts:
        - asset: assets/fonts/SJ상큼오렌지.ttf
